//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    
    
    /// <summary>
    /// The PodcastDownloaderConfiguration Configuration Section.
    /// </summary>
    public partial class PodcastDownloaderConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the PodcastDownloaderConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        internal const string PodcastDownloaderConfigurationSectionName = "podcastDownloaderConfiguration";
        
        /// <summary>
        /// The XML path of the PodcastDownloaderConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        internal const string PodcastDownloaderConfigurationSectionPath = "podcastDownloaderConfiguration";
        
        /// <summary>
        /// Gets the PodcastDownloaderConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        public static global::Core.PodcastDownloaderConfiguration Instance
        {
            get
            {
                return ((global::Core.PodcastDownloaderConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::Core.PodcastDownloaderConfiguration.PodcastDownloaderConfigurationSectionPath)));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region MusicPlayer Property
        /// <summary>
        /// The XML name of the <see cref="MusicPlayer"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        internal const string MusicPlayerPropertyName = "musicPlayer";
        
        /// <summary>
        /// Gets or sets the MusicPlayer.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        [global::System.ComponentModel.DescriptionAttribute("The MusicPlayer.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Core.PodcastDownloaderConfiguration.MusicPlayerPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Core.MusicPlayerElement MusicPlayer
        {
            get
            {
                return ((global::Core.MusicPlayerElement)(base[global::Core.PodcastDownloaderConfiguration.MusicPlayerPropertyName]));
            }
            set
            {
                base[global::Core.PodcastDownloaderConfiguration.MusicPlayerPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Core
{
    
    
    /// <summary>
    /// The MusicPlayerElement Configuration Element.
    /// </summary>
    public partial class MusicPlayerElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Path Property
        /// <summary>
        /// The XML name of the <see cref="Path"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        internal const string PathPropertyName = "path";
        
        /// <summary>
        /// Gets or sets the Path.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.2.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Path.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Core.MusicPlayerElement.PathPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Path
        {
            get
            {
                return ((string)(base[global::Core.MusicPlayerElement.PathPropertyName]));
            }
            set
            {
                base[global::Core.MusicPlayerElement.PathPropertyName] = value;
            }
        }
        #endregion
    }
}
